### ISSUE TITLE
NetApp E-Series Check: Error after updating to CheckMK version 2.2

### ISSUE THREAD

**Issue by RobSwoss** [chexma/checkmk_plugins#5]
The update to CheckMK 2.2 failed. I need to delete the NetApp E-Series rule. The cmc core could no longer be started.

Error running automation call restart (exit code 1), error:
An error occurred: Error creating configuration: Traceback (most recent call last):
  File "/omd/sites/mon/lib/python3/cmk/base/cee/microcore_config.py", line 2136, in _hosts_worker
    hosts_data = _compute_worker_hosts_data(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/mon/lib/python3/cmk/base/cee/microcore_config.py", line 2027, in _compute_worker_hosts_data
    return [
           ^
  File "/omd/sites/mon/lib/python3/cmk/base/cee/microcore_config.py", line 2028, in <listcomp>
    helper_config_manager.get_host_data(
  File "/omd/sites/mon/lib/python3/cmk/base/cee/microcore_config.py", line 2903, in get_host_data
    return self._compute_and_cache(host_class(hostname, stored_passwords))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/mon/lib/python3/cmk/base/cee/microcore_config.py", line 2959, in _compute_and_cache
    self._write_host_fetcher_config(host.hostname)
  File "/omd/sites/mon/lib/python3/cmk/base/cee/microcore_config.py", line 2964, in _write_host_fetcher_config
    fetcher_config.write_local(self._config_path, hostname)
  File "/omd/sites/mon/lib/python3/cmk/base/cee/fetcher_config.py", line 33, in write_local
    serialized = fetcher_configuration.fetchers(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/mon/lib/python3/cmk/cee/helpers/fetcher_configuration.py", line 45, in fetchers
    "fetchers": [
                ^
  File "/omd/sites/mon/lib/python3/cmk/cee/helpers/fetcher_configuration.py", line 45, in <listcomp>
    "fetchers": [
                ^
  File "/omd/sites/mon/lib/python3/cmk/cee/helpers/fetcher_configuration.py", line 30, in _unpack
    source.fetcher(),
    ^^^^^^^^^^^^^^^^
  File "/omd/sites/mon/lib/python3/cmk/base/_sources.py", line 389, in fetcher
    cmdline=self.config_cache.make_special_agent_cmdline(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/mon/lib/python3/cmk/base/config.py", line 2789, in make_special_agent_cmdline
    args = _make_source_args(
           ^^^^^^^^^^^^^^^^^^
  File "/omd/sites/mon/lib/python3/cmk/base/config.py", line 2784, in _make_source_args
    agent_configuration = info_func(params, hostname, ip_address)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/mon/local/share/check_mk/checks/agent_netappeseries", line 20, in agent_netappeseries_arguments
    args += "-u " + quote_shell_string(params["user"])
                    ^^^^^^^^^^^^^^^^^^
NameError: name 'quote_shell_string' is not defined

Traceback (most recent call last):
  File "/omd/sites/mon/lib/python3/cmk/base/cee/microcore_config.py", line 2136, in _hosts_worker
    hosts_data = _compute_worker_hosts_data(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/mon/lib/python3/cmk/base/cee/microcore_config.py", line 2027, in _compute_worker_hosts_data
    return [
           ^
  File "/omd/sites/mon/lib/python3/cmk/base/cee/microcore_config.py", line 2028, in <listcomp>
    helper_config_manager.get_host_data(
  File "/omd/sites/mon/lib/python3/cmk/base/cee/microcore_config.py", line 2903, in get_host_data
    return self._compute_and_cache(host_class(hostname, stored_passwords))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/mon/lib/python3/cmk/base/cee/microcore_config.py", line 2959, in _compute_and_cache
    self._write_host_fetcher_config(host.hostname)
  File "/omd/sites/mon/lib/python3/cmk/base/cee/microcore_config.py", line 2964, in _write_host_fetcher_config
    fetcher_config.write_local(self._config_path, hostname)
  File "/omd/sites/mon/lib/python3/cmk/base/cee/fetcher_config.py", line 33, in write_local
    serialized = fetcher_configuration.fetchers(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/mon/lib/python3/cmk/cee/helpers/fetcher_configuration.py", line 45, in fetchers
    "fetchers": [
                ^
  File "/omd/sites/mon/lib/python3/cmk/cee/helpers/fetcher_configuration.py", line 45, in <listcomp>
    "fetchers": [
                ^
  File "/omd/sites/mon/lib/python3/cmk/cee/helpers/fetcher_configuration.py", line 30, in _unpack
    source.fetcher(),
    ^^^^^^^^^^^^^^^^
  File "/omd/sites/mon/lib/python3/cmk/base/_sources.py", line 389, in fetcher
    cmdline=self.config_cache.make_special_agent_cmdline(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/mon/lib/python3/cmk/base/config.py", line 2789, in make_special_agent_cmdline
    args = _make_source_args(
           ^^^^^^^^^^^^^^^^^^
  File "/omd/sites/mon/lib/python3/cmk/base/config.py", line 2784, in _make_source_args
    agent_configuration = info_func(params, hostname, ip_address)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/mon/local/share/check_mk/checks/agent_netappeseries", line 20, in agent_netappeseries_arguments
    args += "-u " + quote_shell_string(params["user"])
                    ^^^^^^^^^^^^^^^^^^
NameError: name 'quote_shell_string' is not defined

**Comment by chexma** [comment]
Hi Rob,

the plugin is not yet compatible with checkmk version 2.2 yet, as there are some breaking changes how mkps work.
I will have to rewrite some parts, i hope to take a look this weekend.

**Comment by RobSwoss** [comment]
@chexma Any news?

**Comment by chexma** [comment]
Hi Rob,

i updated the version to work with checkmk 2.2. It is not fully migrated to the new api but it should work.
I was only able to test it locally with my test data, as i currently have no access to real e-series systems, so please test it before using it in production.
If you are in the checkmk forum, you can contact me there.

**Comment by RobSwoss** [comment]
Worked. Many many thanks!
